name: CloneMe
main: com.worldcretornica.cloneme.CloneMe
version: '0.11'
author: ZachBora
website: http://dev.bukkit.org/server-mods/cloneme/
depend: [Citizens]
softdepend: [NoCheatPlus]
description: >
             Create clones to help you build
commands:
    cloneme:
        description: List cloning commands
        usage: /cloneme
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
        aliases: [clone,c]
    cloneme stop [player]:
        description: Removes your clones or someone else's
        usage: /cloneme stop [player]
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme stopall:
        description: Removes every clones
        usage: /cloneme stopall
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme reload:
        description: Reloads plugin
        usage: /cloneme reload
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme add:
        description: Adds a clone
        usage: /cloneme add
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme modify:
        description: Modifies a clone
        usage: /cloneme modify
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme ready:
        description: Start your clones
        usage: /cloneme ready
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme pause:
        description: Pauses your clones
        usage: /cloneme pause
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme limit:
        description: Limit the distance of your clones
        usage: /cloneme limit
        permission: CloneMe.use
        permission-message: You do not have permission to use Clones
    cloneme players:
        description: Lists the players with clones
        usage: /cloneme players
        permissions: CloneMe.use
        permission-messahe: You do not have permission to use Clones
        
permissions:
    CloneMe.*:
        description: Allows you to use everything in the CloneMe plugin.
    CloneMe.use:
        description: Allows you to use Clones.
    